---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero

platforms:
  - name: centos-7
    driver_config:
      provision_command:
        #- yum -y swap -- remove systemd-container systemd-container-libs -- install systemd
        - yum -y install iproute
      run_command: /usr/sbin/init
      privileged: true

suites:
  - name: default-client
    run_list:
      - recipe[pg::client]
  - name: default-server
    run_list:
      - recipe[pg::server]
  - name: pgdg-client
    run_list:
      - recipe[pg::client]
    attributes:
      pg:
        use_pgdg: true
        pgdg:
          version: '9.5'
  - name: pgdg-server
    run_list:
      - recipe[pg::server]
    attributes:
      pg:
        use_pgdg: true
        pgdg:
          version: '9.5'
  - name: pgbouncer
    run_list:
      - recipe[pg::pgbouncer]
    attributes:
      pg:
        use_pgdg: true
        pgdg:
          version: '9.5'
  - name: pgpool
    run_list:
      - recipe[pg::pgpool]
    attributes:
      pg:
        use_pgdg: true
        pgdg:
          version: '9.5'
        config:
          pcp:
            admin: 'foobar'
